FROM node:20-alpine

WORKDIR /app

RUN apk add --no-cache git && \
    git clone https://github.com/lucas-gil/whatsapp-chatbot.git . && \
    npm install

WORKDIR /app/apps/api

EXPOSE 3000

CMD ["npm", "start"]
